name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          rm -rf node_modules
          rm -f package-lock.json
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t naveenk92/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true naveenk92/docker-react npm run test